version: "3"
services:
    php:
        build: .
        ports:
         - "8027:80"
        volumes:
         - .:/var/www/html
        links:
         - db
    db:
        image: mysql:5.7
        volumes:
            - .:/docker-entrypoint-initdb.d
            - /var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=test
            - MYSQL_DATABASE=cktdb